### ISSUE TITLE
Error when tried yarn install in src/worker

### ISSUE THREAD

**Issue by kanagas3** [stuartsan/lighthouse-lambda-parallel#4]
error /home/ec2-user/lighthouseLambda/lighthouse-lambda-parallel/lambdas/src/worker/node_modules/@serverless-chrome/lambda: Command failed.
Exit code: 1
Command: node scripts/postinstall.js
Arguments: 
Directory: /home/ec2-user/lighthouseLambda/lighthouse-lambda-parallel/lambdas/src/worker/node_modules/@serverless-chrome/lambda
Output:
Downloading precompiled headless Chromium binary (stable channel) for AWS Lambda.
Error: connect ETIMEDOUT 13.XXX.44.5:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '13.XXX.44.5',
  port: 443
}

**Comment by kanagas3** [comment]
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module '@serverless-chrome/lambda/dist/headless-chromium'\nRequire stack:\n- /var/task/create-lighthouse.js\n- /var/task/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module '@serverless-chrome/lambda/dist/headless-chromium'",
        "Require stack:",
        "- /var/task/create-lighthouse.js",
        "- /var/task/index.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:1133:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)",
        "    at Module.load (internal/modules/cjs/loader.js:977:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:877:14)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)",
        "    at internal/main/run_main_module.js:18:47"
    ]
}
